### ISSUE TITLE
Solution for large ids by adding O(1) lookup

### ISSUE THREAD

**Issue by jpotts18** [Doist/bitmapist#23]
In your documentation it reads:

> Using Redis bitmaps you can store events for millions of users in a very little amount of memory (megabytes). You should be careful about using huge ids (e.g. 2^32 or bigger) as this could require larger amounts of memory.

It might be a potential solution to create a hash table that keeps track of huge ids and maps them back down to smaller indexes.

For example, a user with an id of 192329230202 could be mapped to a smaller index 1 in the bitmap. This would require an O(1) lookup before a `SETBIT' so it shouldn't affect time performance, but it would require more space on disk. 

Steps to implement:

1. A new user performs an signup event. 
1. Find the users_counter for the current day `GET "users_counter:20160614"` which would respond back with something like 2. 
1. Add new `User(id:192329230202)` to the `user_index` table and reassign to `User(internal_id:3)`. This would do something like `SET "users_index:20160614:192329230202" 3`
1. Once this is completed successfully you would want to run `INCR users_count:20160614`
1. `SETBIT "events:search:20160614" 3 1` bit into feature signup at `User(3)` index instead of at the end of the bitmap which requires creating and storing empty bits. 

This would most likely add complexity into how your query the data and you would have to store a reference to lookup each user. In my proposal I used a different lookup per day to reset the bitmap indexes everyday, but this might be more trouble than just maintaining one large ongoing table.

Let me know your thoughts and if this something you are interested in promoting into an enhancement.

**Comment by imankulov** [comment]
Hey @jpotts18!

As far as I'm concerned, this functionality "breaks the bitmap magic" when it comes to processing records from different dates, because each day the same uid is mapped to different "small values", and the processing of queries such as "how many users were active two days in a row, both yesterday and today" turns into a non-trivial exercise (not only in terms of programming, but mostly in terms of performance). In order to operate properly, bitmapist must keep user ids the same (bits must be set in the same positions in each Redis key).

There is a trick though. If you want to keep Redis memory under control, care more about "mass values" rather than individual values, then you can convert big uids (or even string uids, or whatever) to integers right from the Python with something like

```python
import random
bitmapist_uid = random.Random(my_long_uid).randint(1, 1000)
```

Depending on your case it may or may not be appropriate :)
